language: android
# Use the Travis Container-Based Infrastructure
sudo: false
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/caches/2.10
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
env:
  global:
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
    - ADB_INSTALL_TIMEOUT=8
before_install:
  # Add licenses to Android SDK
  - echo "$ANDROID_HOME"
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
android:
  components:
    # Latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.1

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
# Emulator Management: Create, Start and Wait
before_script:
  # Emulator creates a 32MB SD card file to store cucumber html/json reports
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -c 32M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 180
  - adb devices
  - adb shell input keyevent 82 &
script:
  - ./gradlew connectedCheck -PdisablePreDex
after_script:
  - echo "Travis TRAVIS_BUILD_DIR:"${TRAVIS_BUILD_DIR}
  - head -200 ${TRAVIS_BUILD_DIR}/app/build/outputs/androidTest-results/connected/*
